### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Delimeng** [yangjianxin1/GPT2-chitchat#126]
Traceback (most recent call last):
  File "D:\desktop\GPT2-chitchat-master\train.py", line 427, in <module>
    main()
  File "D:\desktop\GPT2-chitchat-master\train.py", line 423, in main
    train(model, logger, train_dataset, validate_dataset, args)
  File "D:\desktop\GPT2-chitchat-master\train.py", line 298, in train
    validate_loss = validate_epoch(
  File "D:\desktop\GPT2-chitchat-master\train.py", line 251, in validate_epoch
    epoch_mean_loss = total_loss / len(validate_dataloader)
ZeroDivisionError: division by zero
how to solve the problem?I hope someone can help me.

**Comment by Delimeng** [comment]
问题解决了，是因为自己的语料太少了，可以增加一下语料的数量

**Comment by WThirteen** [comment]
我试着增加语料 但是没有解决。
但是为了让train跑起来 我在分母都加了一个很小的值。  
![image](https://github.com/yangjianxin1/GPT2-chitchat/assets/100677199/21e28366-7bf1-4a6a-8b77-787f119d03eb)
代码确实是跑起来了

**Comment by Delimeng** [comment]
1，他这个报错的原因就是分母的值为零，你加上一个很小的值确实会避免这个错误，但是对于模型的训练来说准确度很重要。
2，另外增加语料没有解决这个问题的话，还是你增加的语料的数量太少了，我的建议是你不要手动去增加语料，你去作者的链接里面找一下，我记得有语料的压缩包，把它下载下来。

**Comment by Delimeng** [comment]
1.他这个报错的原因就是分母的值为零，你在分母上加上一个很小的值确实会避免这个错误，但是对于模型的训练来说准确度很重要。2。另外增加语料还是没有解决这个问题的原因是你的语料增加的还是不够多，我的建议是你不要手动的去增加语料，你去作者的链接里面找找看，我记得有语料的压缩包，你把他下载下来就行，






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月16日(星期二) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangjianxin1/GPT2-chitchat] ZeroDivisionError: division by zero (Issue #126)














 
我试着增加语料 但是没有解决。
 但是为了让train跑起来 我在分母都加了一个很小的值。
 image.png (view on web)
 代码确实是跑起来了

**Comment by WThirteen** [comment]
我在分母增加最小值的方法确实不可取： 导致后面训练的模型使用出现乱码：
![image](https://github.com/yangjianxin1/GPT2-chitchat/assets/100677199/2f425d01-3798-40a0-9a9b-36435f550391)
我再尝试去增加语料，谢谢你

**Comment by Delimeng** [comment]
不客气，





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月17日(星期三) 凌晨2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangjianxin1/GPT2-chitchat] ZeroDivisionError: division by zero (Issue #126)














 
我在分母增加最小值的方法确实不可取： 导致后面训练的模型使用出现乱码：
 image.png (view on web)
 我再尝试去增加语料，谢谢你
