### ISSUE TITLE
 读如train.txt的时候报错，说utf8无法解码

### ISSUE THREAD

**Issue by MozarTuring** [yangjianxin1/GPT2-chitchat#52]

**Comment by MozarTuring** [comment]
大家没碰到这个问题吗

**Comment by telunyang** [comment]
> 大家没碰到这个问题吗

是不是出現 cpXXX 之類的訊息?
我之前也有類似的問題，當時在 conda 環境下，我用 python 指令直接下，會有問題，但直接用 python3.7 這個原生指令，竟然就可以了。

**Comment by GaloisGroGauss** [comment]
> 大家没碰到这个问题吗

Traceback (most recent call last):
  File "interact.py", line 177, in <module>
    main()
  File "interact.py", line 135, in main
    text = input("user:")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 3: invalid continuation byte

**Comment by chenyiwan** [comment]
因为你的train.txt 是GBK编码 。要换成UTF-8
