### ISSUE TITLE
python interact_mmi.py报错

### ISSUE THREAD

**Issue by rorsarach** [yangjianxin1/GPT2-chitchat#57]
Traceback (most recent call last):
  File "interact_mmi.py", line 223, in <module>
    main()
  File "interact_mmi.py", line 159, in main
    next_token_logit[tokenizer.convert_tokens_to_ids('[UNK]')] = -float('Inf')
RuntimeError: Output 1 of UnbindBackward is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views
. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by MRXY001** [comment]
我也是这个错误

**Comment by sharon880701** [comment]
將pytorch 降到version 1.3.0就可以了

**Comment by michael-destiny** [comment]
next_token_logits = outputs[0][:, -1, :].clone().detach()

**Comment by KaishuaiXu** [comment]
使用with torch.no_grad():就可以了
