### ISSUE TITLE
训练模型遇到cannot allocate memory

### ISSUE THREAD

**Issue by chiangandy** [yangjianxin1/GPT2-chitchat#65]
我用50W的语料训练模型，
我在一般mac环境用6GB RAM是可以运行，但跑了3个小时第一个eporch都还没跑完...
然后我改用有cuda的机器跑～
却遇到以下错误...

andy@andy-nano:~/GPT2-chitchat-master$ python3 train.py --epochs 30 --batch_size 8
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2021-03-16 14:16:30.745458: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
2021-03-16 14:16:54,729 - INFO - using device:cuda
2021-03-16 14:17:11,152 - INFO - model config:
{
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "finetuning_task": null,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 300,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 10,
  "n_positions": 300,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torchscript": false,
  "use_bfloat16": false,
  "vocab_size": 13317
}

2021-03-16 14:18:05,492 - INFO - number of model parameters: 81338112
2021-03-16 14:18:05,510 - INFO - loading traing data
2021-03-16 14:18:16,990 - INFO - total training steps = 1500000
2021-03-16 14:18:17,510 - INFO - starting training
Traceback (most recent call last):
  File "train.py", line 447, in <module>
    main()
  File "train.py", line 441, in main
    train(model, device, train_list, multi_gpu, args)
  File "train.py", line 293, in train
    for batch_idx, input_ids in enumerate(train_dataloader):
  File "/home/andy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/home/andy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/andy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

看来我的cuda 环境太简陋了，无法撑住运行...
我的cuda只有4GB Ram...会是主要原因吗？
请教一下，你训练模型使用的硬件环境是多大？ 总共运行了多久？ 想说接下来采购硬件有个参考～

感谢了

**Comment by yangjianxin1** [comment]
用一张GTX 1080Ti可以跑小一点的batch size，两张的话，可以跑大一点的batch size

**Comment by chiangandy** [comment]
请问一张GTX 1080Ti 是跑多少batch size? 花了多久时间跑完？

**Comment by yangjianxin1** [comment]
一张1080Ti的话，batch_size设置不了很大，这个你可以自己试着调一下

**Comment by sealhuang** [comment]
我用一张2080Ti，输入长度150，batch size只能跑8
