### ISSUE TITLE
error---->train.py

### ISSUE THREAD

**Issue by KangChou** [yangjianxin1/GPT2-chitchat#85]
python train.py --epochs 1 --batch_size 2 --device 0 --train_path data/train_2w.pkl

```
th='data/train.log', log_step=1, lr=2.6e-05, max_grad_norm=2.0, max_len=150, model_config='config/config.json', no_cuda=False, num_workers=0, pad_id=0, patience=0, pretrained_model='', save_model_path='model', sep_id=102, train_path='data/train_2w.pkl', val_num=8000, vocab_path='vocab/vocab.txt', warmup_steps=200)
2021-11-30 13:46:19,241 - INFO - loading training dataset and validating dataset
Traceback (most recent call last):
  File "train.py", line 427, in <module>
    main()
  File "train.py", line 423, in main
    train(model, logger, train_dataset, validate_dataset, args)
  File "train.py", line 270, in train
    drop_last=True
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 266, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

```

**Comment by Saraooe** [comment]
train.py 348行改成  input_ids = input_ids.to(device)

**Comment by Dynamicboboo** [comment]
解决了吗？

**Comment by eurethia** [comment]
> train.py 348行改成 input_ids = input_ids.to(device)

348行是“def calculate_acc(logit, labels, ignore_index=-100):”,这可怎么改..

**Comment by eurethia** [comment]
我也遇到这个问题了，好奇怪啊

**Comment by FuryMartin** [comment]
> 我也遇到这个问题了，好奇怪啊

见：https://github.com/yangjianxin1/GPT2-chitchat/issues/79#issuecomment-941684250 中 [r1cebank](https://github.com/r1cebank) 的回答
