### ISSUE TITLE
自定义语料 报错ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Dynamicboboo** [yangjianxin1/GPT2-chitchat#89]
2022-02-28 16:58:29,654 - INFO - using device:cpu
[Warning] The warmup steps may be not enough.
(sz_b, warmup) = (2048, 4000) is the official setting.
Using smaller batch w/o longer warmup may cause the warmup stage ends with only little data trained.
2022-02-28 16:58:31,816 - INFO - model config:
{
  "_name_or_path": "model/epoch29",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "output_past": true,
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 400
    }
  },
  "tokenizer_class": "BertTokenizer",
  "transformers_version": "4.4.2",
  "use_cache": true,
  "vocab_size": 13317
}

2022-02-28 16:58:31,818 - INFO - number of model parameters: 96069888
2022-02-28 16:58:31,819 - INFO - args:Namespace(batch_size=2, cls_id=101, cuda=False, device='cpu', epochs=1, eps=1e-09, gpu0_bsz=10, gradient_accumulation_steps=4, ignore_index=-100, log=True, log_path='data/train.log', log_step=1, lr=2.6e-05, max_grad_norm=2.0, max_len=150, model_config='config/config.json', no_cuda=False, num_workers=0, pad_id=0, patience=0, pretrained_model='', save_model_path='model', sep_id=102, train_path='data/train.pkl', val_num=8000, vocab_path='vocab/vocab.txt', warmup_steps=4000)
2022-02-28 16:58:31,819 - INFO - loading training dataset and validating dataset
Traceback (most recent call last):
  File "C:/Users/Dynamicboboo/Desktop/GPT2-chitchat-master/train.py", line 427, in <module>
    main()
  File "C:/Users/Dynamicboboo/Desktop/GPT2-chitchat-master/train.py", line 423, in main
    train(model, logger, train_dataset, validate_dataset, args)
  File "C:/Users/Dynamicboboo/Desktop/GPT2-chitchat-master/train.py", line 269, in train
    drop_last=True
  File "C:\Users\Dynamicboboo\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "C:\Users\Dynamicboboo\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Process finished with exit code 1

有遇到的吗

**Comment by GUZIYIN** [comment]
我也遇到了，请问您是怎么解决的？

**Comment by yuxuan2015** [comment]
换成50w的数据就好了
